### PR TITLE
Improves efficiency of extend_cost with an inf cost_limit

### PR DESCRIPTION
**Pull request by raphaelreme**
Hey,

First, thanks a lot for taking care of lap, lapx is so much more user friendly to install now!!

I had noticed in the initial repo (https://github.com/gatagat/lap) that the newest version (undeployed) had introduced some unneeded computations when using extend_cost with an inf cost_limit. I never fixed it because I use my own code fixing it, and there was no one maintaining lap and also it was not deployed on pypi (latest was 0.4.0).

This PR will fix it for lapx. I tested the code on my laptop (ubuntu20.04), it compiles well and do not change the results except the performances (10x faster with extend_cost and cost_limit = inf).

You can have a look at the commit https://github.com/gatagat/lap/commit/cc97e2ebdd2ea275ce94e1a3662b330642005a54 which improved the efficiency with cost_limit < np.inf (using (n + m, n + m) matrices instead of (2 max(n, m), 2 max(n, m)) matrices) but drastically reduced performance when cost_limit == np.inf

Indeed, it also uses (n+m, n+m) matrices where one could only use (max(n, m), max(n,m)) matrices. This will fix this case. (Up to x50 faster)

### CODE REVIEW

**Comment by raphaelreme** [comment]
image

For instance: this is the run time vs the size of the matrix. (Ref is your current version, smallest_fill_inf is more or less what was done in the version 0.4.0 of lap, and smallest_fill_0 is what I did here)

**Comment by rathaROG** [comment]
Hello @raphaelreme , thanks for your nice contribution! According to your benchmark, your pr seems much faster. I will check and do some tests on my parts.

**Comment by rathaROG** [comment]
Hello @raphaelreme , I spent some time look at the code, and I found that `c = np.zeros((n, n), dtype=np.double)` is a lot faster than lines #98-100 

```
c = np.empty((n, n), dtype=np.double)
c[:] = 0
```

image

This drastically improves the speed for `extend_cost=True`. Could you test the current main branch and share the result?

**Comment by raphaelreme** [comment]
Hum I did neglect this because I wanted to keep the same coding style as before and because it should be negligible before the assignment computations. In theory, all this stuff should be O(n**2) and the assignment is O(n**3) (to be checked)

I'll try, it is possible that np.zeros is smarter than np.empty then assigning 0. But in theory, this should be roughly equivalent. In theory I would expect that the fastest solution is to initialize with np.empty then assigning only the added value to 0 and the rest with c. I'll let you know if I'm able to see some speed up on my side too.

**Comment by rathaROG** [comment]
OK I'll keep np.zeros. Many thanks to you again @raphaelreme for this improvement. New v0.5.8 is on the way. 🎉

**Pull request merged**
